### ISSUE TITLE
Ability to call uninit to return the devices back to Synapse

### ISSUE THREAD

**Issue by njbmartin** [CoraleStudios/Colore#101]
In some scenarios, developers may wish to return the devices back to Synapse settings once an effect has been shown.

`NativeWrapper.UnInit()` is currently not a publicly accessible method and should be exposed.

**Comment by Sharparam** [comment]
This would be tricky to implement given the singleton design of Colore. It would mean we need checks in *every single method* to see if the SDK has been initialized before proceeding with any action and re-initing if it needs to.

We can't simply dispose and null the instances either, as someone could've saved an instance locally somewhere which means things will fuck up if those are used again after disposing (there's `ObjectDisposedException` but again means we'd need checks in every single method to see if it's disposed).

**Comment by njbmartin** [comment]
Sadly it's in the SDK for a reason as it can be called at any time. while I agree that someone could save the instance locally, it would therefore be their responsibility to dispose of it after calling `uninit()`.

**Comment by Sharparam** [comment]
Moving this to v4.0 due to the massive structural change required to make any of the proposed solutions work.

**Comment by brandonscott** [comment]
Yes, as mentioned this gives further time to discuss implementations.

**Comment by njbmartin** [comment]
Is there a potential workaround that might work around this?

**Comment by Sharparam** [comment]
As the current design of Colore is singleton, the whole philosophy revolves around a single object instance that dies with the program.

**Comment by brandonscott** [comment]
I shed a tear. :cry:

**Comment by Sharparam** [comment]
We could add an endpoint for `UnInit` but it leaves any behaviour after that point undefined, requires developers to manually keep track of init state, and there's no way to init back.

**Comment by njbmartin** [comment]
viable option?

**Comment by brandonscott** [comment]
Could we give both an `UnInit` and an `Init` method that are marked as being undefined and for advanced use, then tidy up in v4.0?

**Comment by Sharparam** [comment]
Possibly.

**Comment by njbmartin** [comment]
This would certainly be beneficial for myself and the GameDog developer.

**Comment by Sharparam** [comment]
See: #118

**Comment by Sharparam** [comment]
Implemented in #121. Support for this in the actual SDK/Synapse seems to not have been added by Razer yet (was it intended to be there?).

**Comment by brandonscott** [comment]
It was not intended @Sharparam .  The current state is expected behaviour, however it has been noted as a feature request.

**Comment by Sharparam** [comment]
So basically this push to implement (un)init endpoints was completely unwarranted and has achieved nothing except from confusing code that doesn't do what is expected.

**Comment by njbmartin** [comment]
Reopening as the uninit function should call `FreeLibrary(m_ChromaSDKModule)`. This will give back control to Synapse and or other apps.

        [DllImport("kernel32.dll", CharSet=CharSet.Auto, SetLastError=true)]
        public static extern bool FreeLibrary([In] IntPtr hModule);

**Comment by Sharparam** [comment]
@njbmartin Does this mean that the functionality currently works in the non-AnyCPU builds of Colore?

**Comment by njbmartin** [comment]
No effect currently. I think @WolfspiritM mentioned this somewhere.

**Comment by Sharparam** [comment]
We can't use `FreeLibrary` in the x86/x64 builds since there is no library pointer to free there.

**Comment by njbmartin** [comment]
Not sure if this might do the trick in that case?
http://stackoverflow.com/a/11914376

**Comment by Sharparam** [comment]
That would make us able to free it, but as noted in another answer on that question we will not be able to get back to a working state after doing so in the x86/x64 builds as the pinvoker will have an invalid library handle and we can't fix that.

**Comment by njbmartin** [comment]
Will be testing out the sample application to see if I can unit at any time.

**Comment by brandonscott** [comment]
Razer updated their functionality in 1.2.4 to support `Uninit()` as developers would expect.

@Sharparam + @njbmartin: Okay to close?

**Comment by Sharparam** [comment]
We should update the documentation on the `Init`/`Uninit` methods as well.

**Comment by njbmartin** [comment]
Right, so after some testing and verifying with @WolfspiritM, this is confirmed to work really, really nicely.

Important thing to note is when using multiple threads, you should maintain a single global property of IChroma, and initialize / uninitialize that, otherwise it does not uninitialize as expected.

`public static IChroma ci;`

**Comment by Sharparam** [comment]
@njbmartin The `Instance` field in `Chroma` is already static and thread-safe, can you elaborate on the circumstances where accessing it in a multi-threaded environment is unsafe?

**Comment by njbmartin** [comment]
Usage:

I'm using a separate thread for the Lua Runtime, and within that I used `var c = Chroma.Instance;` to ensure it was initialised before the lua scripts made any SDK calls. This was because the lua runtime uses reflection so wasn't initialising Colore correctly.

When calling the uninit method from any other thread, it would stop any further calls, but will continue to show whatever grid/color was set before uninit was called, and was not handing back to Synapse.

By making the change described in my above comment, it behaved as expected and either gave back control to Synapse immediately or after a few seconds.

**Comment by Sharparam** [comment]
This seems to yet again point to the Chroma SDK having issues with calls from a thread other than the one initialization was done on. Is there any official word from Razer about whether their SDK supports multi-threading at all?

**Comment by brandonscott** [comment]
I'll definitely get the answer for this, as I have been wondering about it too.  The Chroma FAQ notes:

> Animations are done in “Frames”. i.e. Frame 1 = No lighting (blank); Frame 2 = Red brightness 50%; Frame 3 = Blue brightness = 100%, etc. Each frame (data) will be send to ChromaSDK sequentially by the client. The period of sending the frames is also determined by the client.
These frame(data) will be forwarded to a background Windows service which communicates with the devices. The frequency of servicing the data is limited to a maximum period of 10ms per frame but is not limited to all devices, as some devices has a lower frequency (2ms).
ChromaSDK and its Windows service runs separately and are independent of each other.

I know it doesn't answer the question here, but it leads me to believe that the client "does it's work" then forwards it to the client, rather than multiple threads accessing the Chroma subsystem at once.  Again, it's just a guess, I'll talk to the engineers.

**Comment by WolfspiritM** [comment]
@Sharparam Yep. That's actually the case. The following sample shows the problem very well even with @njbmartin's fix which worked for him: https://gist.github.com/WolfspiritM/4b66c6c807b16789dfce

Clicking the btnDirect Button everything works fine multiple times.
Clicking the btnNewThread button the Uninit gets stuck.

There is another problem with it even in a non mutilthreading application when you call:
´´´ C#
                Chroma.Instance.SetAll(Corale.Colore.Core.Color.Red);
                Chroma.Instance.Uninitialize();
´´´
The Red Color gets stuck (maybe only on some devices), while the following works:
´´´ C#
                Chroma.Instance.SetAll(Corale.Colore.Core.Color.Red);
                Thread.Sleep(1000);
                Chroma.Instance.Uninitialize();
´´´

**Comment by njbmartin** [comment]
This leads me to believe that the uninit needs to init and occur on the main thread.

@WolfspiritM what happens if you move `if (!ci.Initialized) ci.Initialize();` to within the SetRed method?

**Comment by WolfspiritM** [comment]
@njbmartin Just tried that and it works. Added the working example as another file to the gist: https://gist.github.com/WolfspiritM/4b66c6c807b16789dfce

**Comment by njbmartin** [comment]
@WolfspiritM Did you try Initialising it from the new thread and then unitialising it from the main thread?

**Comment by njbmartin** [comment]
Are we happy that this now works? I haven't had any problems with it and works ok with me :)

**Comment by WolfspiritM** [comment]
Works pretty well as long as Init/Uninit is the same thread.
Has there been a change in latest SDK updates that fixed this?
Might need to try :-)

**Comment by njbmartin** [comment]
Razer have confirmed that the SDK is not particularly thread safe, so while we can init/uninit as above, we must ensure we're doing so in a thread-safe manor.
