### ISSUE TITLE
Check if SDK init function has been called before uninit in finalizer

### ISSUE THREAD

**Issue by Sharparam** [CoraleStudios/Colore#107]
A check should be implemented to prevent invalid calls to `UnInit` in Chroma's finalizer method.

**Comment by brandonscott** [comment]
I'm on "holiday" but couldn't resist. Is there an exposed function for seeing if the SDK is already initialised? Otherwise how could we implement this?

**Comment by Sharparam** [comment]
A boolean flag in Chroma to keep track of if the call to `Init` was successful.

**Comment by brandonscott** [comment]
Do you mean Colore?

**Comment by Sharparam** [comment]
The Chroma class in Colore.

**Comment by brandonscott** [comment]
Ah I see, 'Chroma.cs' to be more specific.  Do we know the interaction between two apps where App A UnInits but App B uses a 'SetFoo' method?

**Comment by Sharparam** [comment]
Chroma.cs is a file that contains the class Chroma (purely because of naming convention and no other reason) which is where the flag needs to be added as a class field. 

Since there haven't (to my knowledge) been issues with apps closing (therefore calling UnInit) followed by other apps continuing operation I'm assuming Razer has something in place to handle it.

**Comment by Sharparam** [comment]
Fixed in #108
