### ISSUE TITLE
Update mouse custom effect to new API

### ISSUE THREAD

**Issue by Sharparam** [CoraleStudios/Colore#110]
The custom effect for the mouse has changed in the later versions of the SDK and is now using a grid like some of the other devices.

The changes includes an enum change to a format similar to that of the keyboard. We have to update the custom effect of the mouse to this new format.

As this is due for the 3.0 release, the old version of the effect should not be kept in Colore, even though the Chroma SDK keeps a backwards-compatible endpoint for it.

Keeping the old way around creates too much confusion, in my opinion, and the change won't be too drastic on Colore users as the public API will be very similar. Input and discussion is of course welcome.

**Comment by njbmartin** [comment]
Sounds good to me!

**Comment by Sharparam** [comment]
Implemented in #116
