### ISSUE TITLE
Razer SDK implementation inconsistent

### ISSUE THREAD

**Issue by Sharparam** [CoraleStudios/Colore#115]
Razer is currently using obsolete code in their own SDK, which is causing issues as to how we are supposed to move forward updating the mouse API.

All the mouse effects *except* for one, the new `CHROMA_CUSTOM2` effect, make use of the `RZLED` enum, which in Razer's documentation is marked as **OBSOLETE**.

It's noted as only being kept to, and I quote: "Maintain backwards compatibility", yet only one part of their SDK makes use of the new "replacement".

This creates a bit of confusion as to how we are supposed to move forward.

**Comment by brandonscott** [comment]
Can we close this in-line with #116?

**Comment by Sharparam** [comment]
We'll close it for now as it seems Razer will be keeping things as they are now for the foreseeable future.
