### ISSUE TITLE
Add temporary method of controlling SDK state

### ISSUE THREAD

**Issue by Sharparam** [CoraleStudios/Colore#118]
* Add endpoint for uninitialising the SDK
 * Add endpoint for initialising the SDK
 * Add property to the Chroma class for checking current init state (basically expose `_initialized`)

Make it clear these methods may result in **undefined behaviour** at any point after a first call to uninitialise the SDK.

**Comment by brandonscott** [comment]
As discussed with @Sharparam and @njbmartin, the sheer amount of people that want this feature warrant an earlier temporary implementation.

**Comment by njbmartin** [comment]
Thanks guys!

**Comment by Sharparam** [comment]
Implemented in #121.
