### ISSUE TITLE
Mouse and Headset have issues with the latest SDK

### ISSUE THREAD

**Issue by njbmartin** [CoraleStudios/Colore#125]
When using SetAll methods, both the mouse and headset don't work.

Mouse throws an error:
`Call to native Chroma SDK function CreateMouseEffect failed with error: RzInvalidParameter: Invalid parameter. (87)`

Headset fails silently.

**Comment by njbmartin** [comment]
Need to investigate the Headset issue.

**Comment by njbmartin** [comment]
As in, haven't had chance yet as mouse was priority.

**Comment by njbmartin** [comment]
Well the headset is an interesting one.

Simply calling `Headset.Instance.SetAll(Color.Blue)` does nothing, until you interact with another device.

            Headset.Instance.SetAll(Color.Red);

Does nothing. Followed by:

            Keyboard.Instance.SetAll(Color.Blue);

Sets the Keyboard to Blue, and now sets the headset to Red. If you do it the other way around, it works fine / as expected.

Here is how I tested this:

            Headset.Instance.SetAll(Color.Yellow);
            Thread.Sleep(3000);
            Keyboard.Instance.SetAll(Color.Blue);

As described above, Headset does nothing for 3 seconds until the Keyboard is set to Blue.

**Comment by Sharparam** [comment]
And if you set keyboard first, a subsequent call to `Headset.SetAll` works?

**Comment by njbmartin** [comment]
Yep. It's like it hasn't been instantiated

**Comment by Sharparam** [comment]
If it hadn't been instantiated you'd get a `NullReferenceException` when trying to access `SetAll`. Seems more likely the SDK is for some reason ignoring the headset call if that is the first one and only handling it when another device has been accessed.

What about calling headset's `SetAll` twice?

**Comment by njbmartin** [comment]
Doesn't work. The C++ sample app works fine.

**Comment by njbmartin** [comment]
Headset.Instance.SetAll(Color.Red);
            Thread.Sleep(1000);
            Headset.Instance.SetAll(Color.Yellow);
            Thread.Sleep(1000);
            Headset.Instance.SetAll(Color.Green);
            Thread.Sleep(1000);
            Headset.Instance.SetAll(Color.Blue);
            Thread.Sleep(1000);
            Keyboard.Instance.SetAll(Color.Blue);

As described above, does nothing until Keyboard is set. No errors.

**Comment by njbmartin** [comment]
Also, this applies to all of Headset's effects, not just SetAll

**Comment by Sharparam** [comment]
And is the sample app creating other effects before touching headset?

**Comment by njbmartin** [comment]
Nothing is standing out for me as to why this is happening, so not sure if it's the SDK or Colore.

**Comment by WolfspiritM** [comment]
For the mouse issue: I'd suggest replacing

```C#
        public override void SetAll(Color color)
        {
            // We update both the Custom and CustomGrid effect to keep them both
            // as synced as possible.
            _custom.Set(color);
            _customGrid.Set(color);
            SetGrid(_customGrid);
        }
```
with
```C#
        public override void SetAll(Color color)
        {
            // We update both the Custom and CustomGrid effect to keep them both
            // as synced as possible.
            _custom.Set(color);
            _customGrid.Set(color);
            SetCustom(_custom);
        }
```

As the Custom value didn't move between the SDK Versions this will ensure at least SetAll works for different SDK Versions and it doesn't matter in this case.

**Comment by Sharparam** [comment]
@WolfspiritM Post hotfix #127 it won't matter anyway. Unless of course Razer is planning on an unannounced change to the ordering *again*. But if they do we have bigger problems than what method to use for `SetAll`.

**Comment by WolfspiritM** [comment]
@Sharparam Just means SetAll won't be compatible with 1.0.4 anymore without users knowing about that issue (users are forced to update) while with SetCustom it would be compatible with every Version.

**Comment by njbmartin** [comment]
I'm leaning towards the headset issue being an issue on the SDK side and thus does not require a change to Colore. The only thing to do is for devs to workaround the issue until the engineer is back from his lovely holiday.

**Comment by Sharparam** [comment]
@WolfspiritM Colore is aimed to target the latest release of Chroma to always be up to date. If someone for some reason needs to target an older Chroma SDK they can grab an older version of Colore.

It might be useful to add some sort of "tested against SDK ver x.y.z" to Colore, both in docs and in code. So using Colore with an unsupported SDK could print a warning log message. That's a discussion for a separate issue though.

**Comment by njbmartin** [comment]
Yep, it's on Razer to ensure backwards compatibility. It's up to developers to keep up-to-date with Colore.  For example, Colore 2.3.x would continue to work with the SetAll methods.
