### ISSUE TITLE
Fix invalid ordering of mouse effect enum

### ISSUE THREAD

**Issue by Sharparam** [CoraleStudios/Colore#126]
The SDK has changed the ordering of the mouse effect enum members *yet again* and they'll need to be fixed (SDK ver 1.1.2).

References #125.

**Comment by brandonscott** [comment]
A reference note here that the SDK version is 1.1.5 yet the documentation is noted 1.1.2 as it didn't change in those 3 *patch* versions.  This doesn't affect this issue, but is useful to know.

**Comment by Sharparam** [comment]
Was this fixed or was it found out that it wasn't needed?

**Comment by Sharparam** [comment]
The enum in the 1.1.5 docs match what we currently have in Colore, so I'll close this. It must've been fixed at one point and we forgot to update this issue.
