### ISSUE TITLE
Calling Chroma.Query on a Razer Deathstalker GUID causes exception

### ISSUE THREAD

**Issue by roxaskeyheart** [CoraleStudios/Colore#128]
When calling a Query using the Razer Deathstalker Chroma GUID:

0x18c5ad9b, 0x4326, 0x4828, 0x92, 0xc4, 0x26, 0x69, 0xa6, 0x6d, 0x22, 0x83

Causes the following exception:

Corale.Colore.Razer.NativeCallException: Call to native Chroma SDK function QueryDevice failed with error: RzNotSupported: Not supported. (50) ---> System.ComponentModel.Win32Exception: The request is not supported
   --- End of inner exception stack trace ---
   at Corale.Colore.Core.NativeWrapper.QueryDevice(Guid id)
   at Corale.Colore.Core.Chroma.Query(Guid deviceId)

---

Have tested with other Chroma devices and Query seems to operate fine with them. Also other methods such as setting colours seem to work on the Deathstalker as well.

**Comment by technicaldaniel** [comment]
Same issue also seems to occur when using the Diamondback GUID as well

**Comment by Sharparam** [comment]
Are the GUIDs in Colore and the SDK matching? They should be but with the
recent unannounced changes in the SDK who knows. I won't be on a proper
computer until later tonight so I can't currently check.

**Comment by technicaldaniel** [comment]
According to the documentation found in the Razer SDK 1.04 the GUIDs should be:

// {FF8A5929-4512-4257-8D59-C647BF9935D0}
static const GUID DIAMONDBACK_CHROMA= 
{ 0xff8a5929, 0x4512, 0x4257, { 0x8d, 0x59, 0xc6, 0x47, 0xbf, 0x99, 0x35, 0xd0 } };
}

// {18C5AD9B-4326-4828-92C4-2669A66D2283}
static const GUID DEATHSTALKER_CHROMA = 
{ 0x18c5ad9b, 0x4326, 0x4828, { 0x92, 0xc4, 0x26, 0x69, 0xa6, 0x6d, 0x22, 0x83 } };

This does appear to be correct in Colore as well on first inspection.

**Comment by Sharparam** [comment]
Are they able to be queried using the C++ SDK?

**Comment by technicaldaniel** [comment]
I am unable to verify this due to lack of knowledge of C++

**Comment by Sharparam** [comment]
Tagging @brandonscott and @njbmartin, please test in C++. I probably won't
be home until pretty late.

**Comment by njbmartin** [comment]
Will test within the next hour.

**Comment by brandonscott** [comment]
This fails in the SDK also (C++).  I'll raise it with Razer.

**Comment by brandonscott** [comment]
Fix prepared by Razer.  Requires testing.

**Comment by brandonscott** [comment]
Seems to be fixed in SDK 1.2.4.
