### ISSUE TITLE
SetReactive Method Inconsistent

### ISSUE THREAD

**Issue by brandonscott** [CoraleStudios/Colore#134]
The `SetReactive(Color, Duration)` is inconsistent between `Keyboard` and `Keypad`.

Keyboard: `SetReactive(Color, Duration)`
Keypad: `SetReactive(Duration, Color)`

This should be changed so it is consistent across both classes.

**Comment by Sharparam** [comment]
Keypad's definition should be changed to match that of keyboard "react with color X for duration Y" <- feels the most natural to me. Thoughts?

**Comment by brandonscott** [comment]
Yes I agree, unsure why `Keypad` is different, but we should certainly make it consistent in the next major version.

**Comment by Sharparam** [comment]
Implemented in #135
