### ISSUE TITLE
DeleteCurrentEffect missing on IDevice

### ISSUE THREAD

**Issue by Sharparam** [CoraleStudios/Colore#142]
The method `DeleteCurrentEffect` is missing in the `IDevice` interface.

**Comment by Sharparam** [comment]
Nevermind this, `DeleteCurrentEffect` is internal and we're only using it for internal reasons, general use is the `Clear` method.

**Comment by tjhrulz** [comment]
Any chance you could reevaluate this? Clear sets it to no effect, DeleteCurrentEffect seems to return it back to the default/synapse state.

**Comment by Sharparam** [comment]
As long as it doesn't leave devices in a weird state it should be fine to make them public I guess. Will put it up for discussion and see what comes out of it.

**Comment by njbmartin** [comment]
@tjhrulz think you would be able to give it a go yourself and perhaps submit a PR?

**Comment by tjhrulz** [comment]
I am currently away from a PC where I can build it but sure I'll test it and submit a pull request later this week.

**Comment by tjhrulz** [comment]
After taking a look at it it seems that it is actually functionally the same as clear. Is there a way I could reset a device back to the state it is put in by chroma without deinitializing and reinitializing everything? As there seems to be an issue with when I do that whenever I set an effect it ends up being dimmed.
