### ISSUE TITLE
Cannot query Kraken71. Incorrect GUID?

### ISSUE THREAD

**Issue by njbmartin** [CoraleStudios/Colore#149]
Chroma.Instance.Query(Razer.Devices.Kraken71) causes a native call exception

**Comment by Sharparam** [comment]
Exception details?

**Comment by Sharparam** [comment]
Also the GUIDs are the same in Colore and the SDK header files, so the issue is probably somewhere else.

**Comment by njbmartin** [comment]
That's what I thought. Will raise it with Mark.

**Comment by blackworx** [comment]
What's the state on this? Any news?

**Comment by Sharparam** [comment]
Tested it now and querying the Kraken 7.1 still causes an exception.

For reference I do not have a Kraken 7.1, querying a different device that also isn't connected (Deathstalker Chroma) does not cause an exception. Querying a device that is connected (in my case the Blackwidow) also behaves normally.

**Comment by brandonscott** [comment]
@njbmartin: Happy to close?

**Comment by njbmartin** [comment]
Verified in 1.6.x. Closing.
