### ISSUE TITLE
Breathing effects not working correctly in 1.4.1+

### ISSUE THREAD

**Issue by njbmartin** [CoraleStudios/Colore#154]
A [user on insider has noticed a bug](https://insider.razerzone.com/index.php?threads/chroma-sdk-keyboard-breathing-in-c.12646/) with the breathing effect on the keyboard, and upon further investigation myself, it appears to be an issue on a number of different devices including the mouse and keypad. It appears to be an issue with the Chroma SDK itself and not Colore.

`Keyboard`, `Keypad` and `Mouse` breath the first colour twice, ignoring the second value.

  Not sure how long this issue has been there, but... **Please refer to Slack for further findings**

**Comment by njbmartin** [comment]
```
ChromaSDK::Mouse::BREATHING_EFFECT_TYPE CustomEffect = {};
CustomEffect.Type = CustomEffect.TWO_COLORS;
CustomEffect.Color1 = YELLOW;
CustomEffect.Color2 = RED;
CustomEffect.LEDId = RZLED_ALL;
CreateMouseEffect(ChromaSDK::Mouse::CHROMA_BREATHING, &CustomEffect, &Alert);
SetEffect(Alert);
```

As per above, only the yellow is shown. `Color2` is ignored.

**Comment by Sharparam** [comment]
This is known and i think we've contacted Razer about it before, don't
remember if they replied or if they did, what they said about it.

The issue is also only exhibited on certain mice. The effect works fine on
the mamba iirc but the deathadder exhibits the above bug.

**Comment by njbmartin** [comment]
The engineer is currently investigating.

**Comment by njbmartin** [comment]
The engineer at Razer has said the next SDK update will fix these issues. Leaving this open until we're sure no changes to the code is required.

**Comment by njbmartin** [comment]
Verified. Closed.
