### ISSUE TITLE
DeleteEffect should potentially not throw an exception?

### ISSUE THREAD

**Issue by njbmartin** [CoraleStudios/Colore#155]
This is no doubt a very rare use case, but if you have two scripts running and they make a call to the SDK at the same time, it throws an Exception:

`{"Call to native Chroma SDK function DeleteEffect failed with error: Unknown: Unknown. (1168)"}`

While this can be caught in pure C#, its impossible when using a scripting engine. Is it strictly necessary to have it throw an exception instead of just logging?

Or make sure the effect exists before trying to delete it?

**Comment by Sharparam** [comment]
The scripting engine doing the actual communication with Colore should be able to catch the exception? 

In any case this seems like it might be something in the SDK itself too? Isn't it supposed to safely block/ignore calls from apps that are lower in the priority list? (Whichever of the two script apps that have the lowest prio should then be ignored without any error returned.)

**Comment by njbmartin** [comment]
The scripts are still being run from within the same application on separate threads.

**Comment by njbmartin** [comment]
After more investigation, this is the same issue caused when spamming the hell out of the SDK. Seems I would need to work out some way to prioritise the scripts.

When this error occurs, the SDK is no longer accessible and the application needs restarting, even after trying to `Uninitialise` and then `Initialise`.

You're right, this is more of an SDK issue than Colore. Closing this issue.
