### ISSUE TITLE
Use attributes on effect structs to determine type

### ISSUE THREAD

**Issue by Sharparam** [CoraleStudios/Colore#165]
Instead of explicitly specifying the effect type every time we make a call to something like `NativeWrapper.CreateKeyboardEffect(effectType, structInstance)`. We could put an attribute on the effect struct specifying what effect type it uses (so something like `[EffectType(Effect.Custom)]` and then extract that information when setting the type using reflection:

```
public static Guid CreateKeyboardEffect(T @struct) where T : struct
{
  var type = typeof(T).GetAttribute //....
}
```

Reflection is costly, but if we add a way to cache the results this might be feasible to reduce the amount of code we have to maintain. Thoughts?

**Comment by brandonscott** [comment]
Logically makes sense to reduce code, and simplifies effect setting in the back end. Depends on performance really, how do you intend to cache?

**Comment by Sharparam** [comment]
A dictionary to map types to what their respective effect kind is.

**Comment by brandonscott** [comment]
Is this something for v6.0 or for v5.0?  I'd like to get the 1.7.2 changes out there (new grid) as soon as possible so when Razer fixes #168 it'll be ready for our developers.

**Comment by Sharparam** [comment]
This is long-term so it won't be ready until v6.0 at the earliest.

**Comment by Sharparam** [comment]
Closing this as the code for it ends up not being so nice and the fact that I haven't worked on it for over a year.
