### ISSUE TITLE
Incorrect index accessor for Core.Keyboard

### ISSUE THREAD

**Issue by Xinhuan** [CoraleStudios/Colore#169]
https://github.com/CoraleStudios/Colore/blob/master/Corale.Colore/Core/Keyboard.cs#L129

This line:

`return _grid[row - 1, column - 1];`

should probably be

`return _grid[row, column];`

otherwise it throws when using 0 for either row or column.

**Comment by Sharparam** [comment]
I think we forgot to update that line when we switched from 1-based indices to 0-based. The accessor used to be meant for use with 1-MAX indices, but we later changed it but apparently forgot this line.

Not sure how we haven't seen issues related to this crop up until now.
