### ISSUE TITLE
Starlight effect displays nothing

### ISSUE THREAD

**Issue by brandonscott** [CoraleStudios/Colore#172]
As part of #143, the new Starlight effect was implemented.  This results in **nothing** being displayed on the device.  Believed to be an SDK issue and has already been raised by myself to Mark.

**Comment by Sharparam** [comment]
Starlight effect has been implemented on our end, so I'll remove this from the 5.0 milestone but keep it open to track progress of a fix on the SDK side.

**Comment by Sharparam** [comment]
Closing this as new info available in #205.
