### ISSUE TITLE
Query Colore version with Corale.Colore.Version

### ISSUE THREAD

**Issue by njbmartin** [CoraleStudios/Colore#178]
Useful for logging purposes and in cases where the library is not managed by a package manager.

**Comment by Sharparam** [comment]
There are built-in methods in .NET for extracting version from an assembly, so we could add a helper method or property to `Corale.Colore.Core.Chroma` for obtaining it.

**Comment by Sharparam** [comment]
In order to speed up the release of 5.0, I'll move this to the 5.1 milestone. The currently available methods in .NET itself to get the version of an assembly are convenient enough that we can hold off on this feature for a minor release during 5.0.

**Comment by Sharparam** [comment]
Implemented in #201
