### ISSUE TITLE
Handle Macros Key Events

### ISSUE THREAD

**Issue by as206em** [CoraleStudios/Colore#188]
Hi guy's
is there any way to handle macros key events?

**Comment by njbmartin** [comment]
Hey there. While I believe it's not possible, can you elaborate a little bit more about your requirements?

**Comment by as206em** [comment]
i just need to open an app when i press on a Macro key

**Comment by njbmartin** [comment]
Oh, that will be a Synapse feature and nothing to do with Colore. It's definitely possible to do, but this isn't the right place for it.
