### ISSUE TITLE
Clear doesn't work when using internal Custom Effect

### ISSUE THREAD

**Issue by WolfspiritM** [CoraleStudios/Colore#198]
If the internal Custom is used (SetKey(...)) followed by a "Clear" the next call to SetKey will bring back all Keys set before the Clear was executed.  

This seems to be caused by #179 as it only sets the effect to None but the internal Custom is not cleared at the same time.

Clear should also Clear the internal Custom Effect so the next time it gets applied it doesn't bring back previously cleared Keys.

**Comment by Sharparam** [comment]
Fixed in #200
