### ISSUE TITLE
Unable to change color on Razer Man O' War

### ISSUE THREAD

**Issue by Austneal** [CoraleStudios/Colore#202]
Cannot seem to change the color / effect of the Razer Man O' War using `Corale.Colore.Core.Headset.Instance.SetAll` or `Corale.Colore.Core.Chroma.Instance.SetAll`

**Comment by brandonscott** [comment]
Hey @Austneal. This is actually a firmware issue with the product and not Colore. I'll update this when there's a patch.

**Comment by Austneal** [comment]
Awesome response time! You wouldn't happen to have an estimate on that, would you?

**Comment by brandonscott** [comment]
I'll double check and get back to you early next week?

**Comment by Austneal** [comment]
That would be great!

**Comment by Austneal** [comment]
Hey, just checking in to see if there are any updates.

**Comment by Sharparam** [comment]
I've sent off a question about this and am awaiting a response now.

**Comment by Austneal** [comment]
Thanks!

**Comment by Sharparam** [comment]
Confirmed that this is due to firmware bug, the fix is the following:

> Link:
> [dl.razerzone.com/drivers/ManOWar/win/ManO'War_FirmwareUpdater_v31.exe](http://dl.razerzone.com/drivers/ManOWar/win/ManO'War_FirmwareUpdater_v31.exe)
>
> ensure that Synapse is not running while using the update, open the .exe file and follow the instructions there.
>
> It will require you to connect the ManOWar via the cable and having the dongle plugged in as well.

**Comment by Austneal** [comment]
The firmware updater does not seem to work. It instructs me to plug the dongle into my computer, and then attach the headset to the computer via the included charging cable (which I do) and then it gives me two errors in the form of individual popup boxes saying "Please check dongle is plugged in" and "Please check headset is plugged in" immediately afterward.

I've tried running this with the headset turned off and on, running as administrator, and made sure Synapse is not running. Any ideas?

![image 1](https://cloud.githubusercontent.com/assets/5382468/19874465/75dc2806-9f93-11e6-812d-edb4cf1e77ed.png)

**Comment by Sharparam** [comment]
I think it's better to contact Razer support and open an issue with them. Feel free to update here though with what you find!

**Comment by Austneal** [comment]
Will do. I've put in a support ticket, and am awaiting a response now.
