### ISSUE TITLE
Starlight effect has been removed from the SDK

### ISSUE THREAD

**Issue by njbmartin** [CoraleStudios/Colore#205]
`CHROMA_STARLIGHT` has been replaced entirely by `CHROMA_RESERVED`. We should get confirmation from Razer as to whether starlight will make a comeback otherwise we should remove all references to it.

**Comment by Sharparam** [comment]
Seems like they're planning to maybe replace it with something else down the line.

We should probably remove starlight from Colore then and see what happens in the future.

**Comment by njbmartin** [comment]
Alright, I'll go ahead and do this tonight.

**Comment by Sharparam** [comment]
Related: #172

**Comment by Sharparam** [comment]
Fixed in #207
