### ISSUE TITLE
Documentation Website Down.

### ISSUE THREAD

**Issue by abrad1212** [CoraleStudios/Colore#208]
While developing with this AMAZING LIBRARY I came to find that your documentation website is down

[MainPage](http://coralestudios.com/)
[Documentation Page](http://colore.coralestudios.com/docs/)

Thanks!

**Comment by Sharparam** [comment]
Ping @brandonscott

**Comment by abrad1212** [comment]
[Ok It's back up!](http://colore.coralestudios.com/docs/struct_corale_1_1_colore_1_1_razer_1_1_keypad_1_1_effects_1_1_breathing.html)

**Comment by Sharparam** [comment]
Yep. Domain is renewed now!
