### ISSUE TITLE
SDK no longer being uninitialized

### ISSUE THREAD

**Issue by njbmartin** [CoraleStudios/Colore#210]
Raised this with Razer already, but the SDK no longer hands back full control to Synapse when uninitialized.

Logging this for tracking purposes.

**Comment by abrad1212** [comment]
How do you know how to do all of this stuff, like writing this library that interacts with an API? It just blows my mind how talented people are and what they can make with computers. Me I know little C# and develop with Unity 😄. Keep up the good work with this library!

I have one question is this team like
College Students or Graduates

**Comment by Sharparam** [comment]
@abrad1212 This is pretty off-topic from this issue, but we're glad you appreciate our work! The [Gitter chat](https://gitter.im/CoraleStudios/Colore) is more suited for general discussions about Colore :)

As for your question, it's a mix between students and people with jobs spending their free time on it!

**Comment by njbmartin** [comment]
I'd love to know more about your unity project. Please get in touch via gitter.

**Comment by njbmartin** [comment]
Closing due to it being an isolated issue.
