### ISSUE TITLE
List of games using Colore

### ISSUE THREAD

**Issue by njbmartin** [CoraleStudios/Colore#212]
We should actively list and promote the games which use the Colore library.

The ones I know so far are:

[![DubWars](http://cdn.akamai.steamstatic.com/steam/apps/290000/capsule_184x69.jpg)](http://store.steampowered.com/app/290000/) [![Masquerada: Songs and Shadows](http://cdn.akamai.steamstatic.com/steam/apps/459090/capsule_184x69.jpg)](http://store.steampowered.com/app/459090/) [![Nevermind](http://cdn.akamai.steamstatic.com/steam/apps/342260/capsule_184x69.jpg)](http://store.steampowered.com/app/342260/)
[![Please, Don't Touch Anything 3D](http://cdn.akamai.steamstatic.com/steam/apps/529590/capsule_184x69.jpg)](http://store.steampowered.com/app/529590/) [![Starcrawlers](http://cdn.akamai.steamstatic.com/steam/apps/318970/capsule_184x69.jpg)](http://store.steampowered.com/app/318970/) [![The Little Acre](http://cdn.akamai.steamstatic.com/steam/apps/423590/capsule_184x69.jpg)](http://store.steampowered.com/app/423590/)

And yes, that took longer than i thought making it all pretty.

**Comment by Mockarutan** [comment]
www.Battlerite.com uses it :)

I also just wrote support for Chroma Link that Razer wants us to get, and then submitted a pull request for it here.

**Comment by Sharparam** [comment]
I'll close this since games have been added now. Adding new ones will be seen as something we do constantly as we discover them.

**Comment by Sharparam** [comment]
@roxaskeyheart Feel free to add links to your projects :)
