### ISSUE TITLE
Unity keeps crashing - workaround

### ISSUE THREAD

**Issue by njbmartin** [CoraleStudios/Colore#216]
It's been an issue for some time in which the Unity Editor will randomly crash when using the plugin.

> we're still encountering crashes occasionally, usually after a code recompile when Unity attempts to refresh plugins

It seems the plugin gets initialised when you play a Chroma enabled scene in the editor, but stopping the scene will not uninitialise it as the application doesn't actually quit.

As a workaround, and possibly the only solution to the problem, is to manually unitialise `onApplicationQuit`.

```c#
    void OnApplicationQuit()
    {
        Chroma.Instance.Uninitialize(); 
    }
```

I'll try and see if the Unity engineers can look into it further, but may require sending them hardware.

**Comment by Sharparam** [comment]
I'll close this as the listed workaround seems simple enough to implement. If there's any new info on this, feel free to re-open.
