### ISSUE TITLE
Unable to set Corale.Colore.Core.Color in Unity Inspector 

### ISSUE THREAD

**Issue by charblar** [CoraleStudios/Colore#220]
Hey, I recently learned about Colore with my new keyboard and decided to take it for a spin in Unity! However I seem to have run into a problem in which I am unable to set the color unless I hard code it in as it will not appear in the inspector otherwise, I've included my code bellow any help is greatly appreciated!

(Using Unity 5.5.0f3)
```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
//corale
using Corale.Colore.Core;
using Corale.Colore.Razer.Keyboard;
using ColoreColor = Corale.Colore.Core.Color;

public class ColoreTest : MonoBehaviour {

    public LayerMask mask; //appears (just an example that isn't a float or string which I know unity UI can handle
    public ColoreColor color; //doesn't appear

    //appears in unity under functions that can be called via OnClick(), doesn't do anything obviously as color isn't set
    public void SetAll_A() {
        //color = ColoreColor.Red; //uncommenting this line will have it work
        Chroma.Instance.SetAll(color);
    }

    //doesn't appear in unity under functions that can be called via on click
    public void SetAll_B(ColoreColor inputColor) {
        Chroma.Instance.SetAll(inputColor);
    }
}
```

**Comment by njbmartin** [comment]
Colore isn't supported in the inspector.

It would be better to use Unity's `color` and convert it to Colore.

**Comment by charblar** [comment]
Thank you very much for a response I was assuming that was the case but I just wanted to make sure I wasn't doing something stupid haha.
