### ISSUE TITLE
Razer Naga Chroma Numpad LED's not working

### ISSUE THREAD

**Issue by roxaskeyheart** [CoraleStudios/Colore#221]
I have noticed I cannot get the side-buttons (defined as Numpad/Backlight in Razer docs) on the Razer Naga Chroma to function from Colore. I am currently using the following code to update the Mouse state, which works for the Scroll Wheel and Logo leds but not the Backlight for some reason?

    RazerApplyMapMouseLighting("ScrollWheel", col, false);
    RazerApplyMapMouseLighting("Logo", col, false);
    RazerApplyMapMouseLighting("Backlight", col, false);

    public void RazerApplyMapMouseLighting(string region, System.Drawing.Color col, bool clear)
        {
            
            uint RzCol = new Corale.Colore.Core.Color(col.R, col.G, col.B);
            if (RazerSDK != false)
            {
                //Send Lighting
                if (RazerDeviceMouse == true)
                {
                    try
                    {
                        Corale.Colore.Razer.Mouse.Led regionid = (Corale.Colore.Razer.Mouse.Led)Enum.Parse(typeof(Corale.Colore.Razer.Mouse.Led), region);
                        Mouse.Instance.SetLed(regionid, RzCol, clear);
                    }
                    catch (Exception) { }
                }
            }
        }

**Comment by Sharparam** [comment]
Does it work if you use `GridLed` to set Backlight?

```
Corale.Colore.Core.Mouse.Instance[GridLed.Backlight] = Color.Red;
```

The `Backlight` enum field has value 3 which is the same as the SDK (ruling out an enum value mismatch error which has happened in the past). It seems this might be an SDK issue. Does setting Backlight via Led (not GridLed) work in C++ using the SDK directly?

**Comment by njbmartin** [comment]
Does sound like an SDK issue. I don't have a Naga Hex, but i have a feeling you two are talking about different devices?

It could be that they've moved over to the Grid though...

**Comment by roxaskeyheart** [comment]
The device I'm referring to is the: http://www.razerzone.com/au-en/gaming-mice/razer-naga-chroma

I'm trying to update the mouse via GridLed but still not getting any results.

I suppose I could have a faulty device, but the logo and scroll wheel still responds?

**Comment by Sharparam** [comment]
As I also had this issue on my Naga (though a different Naga model) it's probably a bug in the SDK, or they mean for developers to move to the `GridLed` solution instead, as that works as expected.

**Comment by njbmartin** [comment]
Just an update, I've finally got a Trello board with Razer to keep track of these issues.

**Comment by Sharparam** [comment]
Has there been any information from Razer whether this behaviour is intended (to deprecate the old LED structure/enum)? @njbmartin

**Comment by Sharparam** [comment]
Since the docs now say that the old LED structure is deprecated, I'll close this issue.
