### ISSUE TITLE
Keyboard.Effects.Breathing does not have a constructor that takes one arguement

### ISSUE THREAD

**Issue by tjhrulz** [CoraleStudios/Colore#224]
Corale.Colore.Razer.Keyboard.Effects.Breathing only accepts giving it two colors. Every other breathing constructor has an option to use just one color. While you can just use the same color twice this is inconsistent with the other options.

**Comment by Sharparam** [comment]
The `EFFECT_BREATHING` for keyboards in the SDK does not have a `BreathingType` that supports single color breathing (unlike some other devices like mice), so the constructor for `Breathing` on keyboard and the relevant helper methods on `IKeyboard` are simply following the SDK conventions.

A constructor that passes the same color to both parameters could be implemented but would be misleading as it doesn't represent an actual supported mode in the SDK.
