### ISSUE TITLE
Fix continuous integration issues

### ISSUE THREAD

**Issue by Sharparam** [CoraleStudios/Colore#228]
The CI server seems to be down for unknown reasons and @brandonscott (server manager) is MIA. If we can't get it back up we will have to look into alternative solutions or spin up a new server somewhere. Problem is a lot of the build configuration was located on that server and that server alone.

If anyone has ideas on possible places to move the build process, please comment on this issue. A third-party build service (so not hosted on a server we control) could improve availability but also limit flexibility and be more expensive.

**Comment by njbmartin** [comment]
https://ci.appveyor.com/project/njbmartin/colore

**Comment by njbmartin** [comment]
Fixed. Just needed to specify the solution file, next step: artefacts!

**Comment by Sharparam** [comment]
I think we'll do some restructuring of the files and add a Cake build script. This will place all the files necessary to build it in the repo, so we can move CI much easier in the future.

After we have the Cake script we can use that in AppVeyor.

**Comment by Sharparam** [comment]
Colore now has a functioning CI infrastructure again using [AppVeyor](https://ci.appveyor.com/project/Corale/colore) and [Travis CI](https://travis-ci.org/CoraleStudios/Colore)!
