### ISSUE TITLE
issues about Duration

### ISSUE THREAD

**Issue by missli93** [CoraleStudios/Colore#239]
1.Why Duration can not be customized
2. Why Breathing's can not be setted duration

**Comment by Sharparam** [comment]
These features are not supported in the SDK, so we can't support them directly in Colore.

What you'd have to do is implement a custom effect that achieves this, using timers and such.

Razer seems to be planning to remove the APIs to make pre-defined effects, so converting your code to use Custom effects is a good move anyway.
