### ISSUE TITLE
Add more Color conversions?

### ISSUE THREAD

**Issue by Sharparam** [CoraleStudios/Colore#25]
In the few apps that so far exist using Colore, a common operation is to convert to/from `System.Drawing.Color`, should we add methods for this on the Color struct?

**Pros:**
 * Able to convert seamlessly between `Color` and `System.Drawing.Color`.

**Cons:**
 * ~~We have to depend on the `System.Drawing` assembly for a single feature.~~

**Potential issues:**
 * Dealing with the alpha component of `System.Drawing.Color`, do we make the converted color darker with more transparent colors?

### Dealing with alpha
This still needs work. If a color is being applied to a cleared keyboard (or where the Color can't possibly be known, such as the first call) we should probably just blend against black. Otherwise we need to blend against the previous color (with respect to the alpha value).

#### Storing alpha value
Can this be stored in the left-most two bytes of the `_value` field? We need to find out if the C++ `COLORREF` struct cares about them.

**Comment by xChris6041x** [comment]
I think it is an okay idea. In my experience with this I decided to make my own color class for alpha values. This relieved me of having to write out the System.Drawing namespace every time I wanted to use the color object (which other developers would have to do because of ambiguity issues). In regards to dealing with alphas I would say no, it is not just making it darker. It should blend with the color below it using the alpha value to see how much of each color is present.

**Comment by Sharparam** [comment]
You raise a good point about setting (semi-)transparent colors when one is already set. It would depend on if the caller wants the color to "overlay" the existing one or replace it entirely.

Something like a boolean `replace` on `Set` methods could be used, but we'll need code to apply blending between colors.

**Comment by njbmartin** [comment]
I definitely like the idea of being able to adjust alpha levels easily.

**Comment by xChris6041x** [comment]
What I did is I have an overloaded method. One took nothing and did just ignored alpha, the other took a color (which black could be passed in for darkening the color) and blended it.

**Comment by Sharparam** [comment]
Updating to add progress.

Open PR with some features relevant to this issue: #30 
[Branch on my fork with added methods to convert to/from System.Drawing.Color via the existing Color struct.](https://github.com/Sharparam/Colore/tree/feature/system-drawing)

**Comment by njbmartin** [comment]
Based on #67, I'd recommend moving to using the `System.Drawing.Color` for presets.

**Comment by brandonscott** [comment]
An updates as to what we might like to do with this?

**Comment by Sharparam** [comment]
We could reduce the pre-defined colors defined by Colore (leaving only Black or maybe Black + White for basic usage).

Problem is since Razer has now said Alpha is *not* supported, we cannot have an implicit conversion between Colore's `Color` and `System.Drawing.Color` as that would imply lost information.

If alpha in Colore's `Color` has to be scrapped we can only have explicit conversion support between the two (as it currently is) and developers would have to write something like:

```c#
Keyboard.Instance.SetAll((Corale.Colore.Core.Color)System.Drawing.Color.Red);
```

**Comment by Sharparam** [comment]
With the development on this issue, the changes suggested would break backwards compatibility with 2.x, moved this to v3.0 milestone.

**Comment by Sharparam** [comment]
Recent changes have implemented most of the stuff discussed here, the casts between Color and other object types are now all implicit and an option to cast to `System.Windows.Media.Color` (used by WPF) has been implemented.

The pre-defined colors are kept for now and stored in a separate file via the use of `partial`, the future of those can be discussed at a later stage in a separate issue.

As for alpha, we just store it in the 4th byte for now, if Razer truly isn't supporting alpha then it should make no difference as it will just be ignored by the SDK.
