### ISSUE TITLE
Fix code style issues

### ISSUE THREAD

**Issue by Sharparam** [CoraleStudios/Colore#292]
There are some issues with the codebase that would be nice to fix:

 * Code style is inconsistent
   - E.g. some places use `x == null` or `x != null` instead of `x is null` and `x is not null`
   - Some places are missing braces around their bodies (like `if`s and other control statements)

There are likely other similar issues given that the code has lived for quite some time by now.

**Comment by fasetto** [comment]
Can you assign this to me please?

**Comment by mingweisoo** [comment]
I am willing to work on this, please assign it to me.

**Comment by Sharparam** [comment]
Sure @fasetto :)

**Comment by Sharparam** [comment]
I'll close this for now, as the code issues outlined in here are fixed now. If I discover more discrepancies I'll create a new issue.
