### ISSUE TITLE
CreateMouseCustomEffects doesn't exist?

### ISSUE THREAD

**Issue by AngeloG** [CoraleStudios/Colore#35]
I'm getting an error on `GetProcAddress` when it gets the function pointer for the function `CreateMouseCustomEffects`, it appears to not exist for me? `CreateMouseEffect` does exist, though.

This is with the Chroma SDK Beta 2.0.

**Comment by Sharparam** [comment]
The new version of the SDK removed some functions and added new ones, the changes [are in the repo](https://github.com/CoraleStudios/Colore/tree/feature/sdk-2.0-support) but I'm awaiting some feedback from other project members before merging in and pushing a release.

**Comment by AngeloG** [comment]
Ah, thank you, I didn't see that branch.
