### ISSUE TITLE
Rework naming of Set methods

### ISSUE THREAD

**Issue by Sharparam** [CoraleStudios/Colore#38]
It was pointed out recently that the extreme number of `Set` overloads can become an issue in more than one way (issue #37 is one example). It can be confusing for developers to figure out which one of the `Set` methods is referred to when quickly glancing over code.

Users without IntelliSense could also find themselves a little lost when writing code.

Perhaps rework this to reduce the number of overloads? Instead of them all being Set, name them SetKey, SetKeys, SetReactive et.c (as a very early iteration of Colore did).

**Comment by brandonscott** [comment]
I agree with re-factoring these methods to have more descriptive names.  There becomes a point where simplicity is a hindrance.  This issue likely came about where there were fewer endpoints in the API in earlier versions of the SDK.

**Comment by Sharparam** [comment]
I'll refactor the names after the 3.5 switch is made.

**Comment by njbmartin** [comment]
Now that people have started to make use of the library, we would need to make sure it doesn't involve too much rewriting on their part (ie. backwards compatibility).

Perhaps these new (old) methods could compliment the existing overloads so that people have could use either?

**Comment by brandonscott** [comment]
We can deprecate them and then remove them as part of v3.x or v4.x depending on when these major releases ship.

**Comment by Sharparam** [comment]
Marking old methods with the `ObsoleteAttribute` would work in most cases, but we're dealing with an extreme amount of them that it would make the file twice as big to keep both.

Possibly version 2.1/2.2 can introduce deprecated methods followed by 3.0 to remove them outright.

**Comment by Sharparam** [comment]
Implemented in #48, further updates will be done in 3.0 when the deprecated methods are being removed.
