### ISSUE TITLE
Grid Not Initialised

### ISSUE THREAD

**Issue by brandonscott** [CoraleStudios/Colore#4]
In the Razer Chroma Types Header (RzChromaSDKTypes.h) the *RZKEY_GRID_LAYOUT* constant is not initialised.

    const COLORREF RZKEY_GRID_LAYOUT[MAX_ROW][MAX_COLUMN] = {};

Tracking this issue here through feedback with Razer.

**Comment by Sharparam** [comment]
Any updates on this?

**Comment by brandonscott** [comment]
Not yet, haven't been able to get hold of an engineer. It's on my list.

**Comment by brandonscott** [comment]
Did the changes in the 0.4x version null this issue?

**Comment by Sharparam** [comment]
AFAIK it doesn't really affect anything. The empty array definition is still in the header files I think, but unsure what it's actually used for.

I think we can close this as a non-issue.
