### ISSUE TITLE
Change .NET Framework target?

### ISSUE THREAD

**Issue by Sharparam** [CoraleStudios/Colore#42]
For increased compatibility, should we consider re-targeting Colore against a lower framework version?

We are not making use of many features exclusive to .NET 4.x and as such it might benefit us to instead target a lower version like 3.5 for increased usability.

First thing will be to make sure what features we are using that are not available on a lower version and if they can be easily replaced with other code.

**Comment by njbmartin** [comment]
Really haven't changed much to make it compatible with .NET Framework 3.5!

     internal Row(IReadOnlyList<Color> colors)

IReadOnlyList is not supported, changed simply to IList.

     var attr = fieldInfo.GetCustomAttribute<DescriptionAttribute>(false);

GetCustomAttribute is not a valid method.

Log4Net also needs to be downgraded, but a version for 2.0 is available on NuGet.

**Comment by njbmartin** [comment]
I don't think we actually lose anything by supporting 3.5+

**Comment by njbmartin** [comment]
Here's the 3.5 compatible version:
https://github.com/CoraleStudios/Colore/compare/develop...njbmartin:feature/DotNet3.5

**Comment by brandonscott** [comment]
Implemented in #45.  Closing.
