### ISSUE TITLE
Cannot set Keypad, Mousepad and Mouse to Effect.None

### ISSUE THREAD

**Issue by njbmartin** [CoraleStudios/Colore#43]
![colore errors](https://cloud.githubusercontent.com/assets/5699471/9903169/f8b1a880-5c6b-11e5-822a-44f448b646e8.PNG)

**Comment by Sharparam** [comment]
Does the SDK itself supports passing `NONE` as the effect? I was under the impression this was some kind of placeholder enum member like the `INVALID` member.

**Comment by Sharparam** [comment]
Fixed in #44
