### ISSUE TITLE
Razer.Devices does not include latest supported devices

### ISSUE THREAD

**Issue by njbmartin** [CoraleStudios/Colore#49]
The following devices are supported by SDK 0.4.8:

* Blackwidow Chroma
* **Blackwidow Chroma TE**
* Deathadder Chroma
* **Mamba Chroma TE**
* Firefly Chroma
* **Tartartus Chroma**
* **Orbweaver Chroma**

Anything in Bold has not yet been added to Razer.Devices.

Also, Colore currently lists the Naga as supported although this has been confirmed as never receiving support.

**Comment by njbmartin** [comment]
Keypads are confirmed to be supported, but haven't been added to Razer.Devices class.

**Comment by brandonscott** [comment]
On top of what @njbmartin observantly mentioned, Blackwidow Chroma TE and Mamba Chroma TE are also supported, yet were also not listed in the Razer.Devices class.

**Comment by Sharparam** [comment]
@brandonscott he already pointed that out.

**Comment by brandonscott** [comment]
@Sharparam He made them bold, but it wasn't in his comment, I was simply being explicit.

**Comment by brandonscott** [comment]
Fixed in #54.

**Comment by Sharparam** [comment]
@brandonscott 

> Anything in Bold has not yet been added to Razer.Devices.

How is that not being explicit.

**Comment by njbmartin** [comment]
my comment was in reference to the conversation we had on Slack where you said you told Mark Keypads were supported.

**Comment by Sharparam** [comment]
Fixed in #54
