### ISSUE TITLE
StyleCop included in NuGet package

### ISSUE THREAD

**Issue by brandonscott** [CoraleStudios/Colore#51]
StyleCop is included in the Corale.Colore package meaning any dependent applications also have StyleCop actioned against it.

Corale should not be forcing developers to abide by the same standards that it itself mandates.  However, it is still of note that StyleCop warnings are there to control best practices and should likely be followed for best quality code.

**Comment by Sharparam** [comment]
PR #50 fixes this.

**Comment by brandonscott** [comment]
The decision was taken after discussion with @Sharparam and @njbmartin to add `developmentDependency="true"` to the NuGet packages.config file, thus removing the StyleCop dependency from this package.
