### ISSUE TITLE
Add helper methods for setting the same effect on multiple devices

### ISSUE THREAD

**Issue by njbmartin** [CoraleStudios/Colore#57]
Right now, to set all devices to the same colour, you need to do this:

     var color = new Corale.Colore.Core.Color(255, 255, 255, 1);
     Headset.Instance.SetAll(color);
     Keyboard.Instance.SetAll(color);
     Keypad.Instance.SetAll(color);
     Mouse.Instance.SetAll(color);
     Mousepad.Instance.SetAll(color);

Would be useful for any effect that is available on multiple devices.

**Comment by Sharparam** [comment]
This should be possible to add for some effects.

Quite a few are not possible though, as several effects use separate config structs or enumerations even though they are virtually the same. A decision I cannot fully understand.

**Comment by Sharparam** [comment]
Added this to 2.2 milestone but we might move it to 3.0 depending on possibilities to implement.

**Comment by brandonscott** [comment]
@Sharparam - You added Ready, does this mean you've implemented it or it's ready to be implemented?

**Comment by Sharparam** [comment]
Means it's ready to be started

**Comment by brandonscott** [comment]
Do we want to do something like `Corale.Colore.Core.All.SetBreathing()`?  Little odd to have an `All.Instance` in my opinion?

**Comment by Sharparam** [comment]
I was thinking simply methods on the `IChroma` interface. `IChroma.SetXXX`.

**Comment by Sharparam** [comment]
So far I have implemented `Chroma.SetAll` but I'm struggling to see how the other effects can be implemented in a good way. Most effects have some differences between devices (Breathing effect for example has either one or two colors, keyboard has two while headset has one).

Anyone got input on other effects that can be made to work like this?

**Comment by brandonscott** [comment]
It begs the question as to why `Headset` implements `Breathing` differently?  What's the rationale for that, do you think?  We could ask Razer to generalise these.

**Comment by Sharparam** [comment]
And why none of the device's effect structs/enums have anything in common when they could very easily do, which would reduce the need to duplicate structs and enums everywhere.

Some of the enums are exactly the same, yet Razer has separate for each device. We could in theory use the same `Direction` enum for Keyboard, Keypad, and Mousepad. But since they are separate in the SDK we can't do that and rely on it working.

**Comment by Sharparam** [comment]
Implemented in #82
