### ISSUE TITLE
Add method to check availability of Chroma SDK

### ISSUE THREAD

**Issue by Sharparam** [CoraleStudios/Colore#59]
Especially for game uses of Colore, it is useful for developers to determine if the Chroma SDK is available on the system, to decide if the game should enable Chroma features.

One way to check for availability is mentioned [on StackOverflow](http://stackoverflow.com/a/2292610/1104531).

**Comment by njbmartin** [comment]
... and any application that is not specifically designed for Chroma users.

**Comment by Sharparam** [comment]
'Tis why I said "**especially for game**" :3
