### ISSUE TITLE
Alpha values within Color not working as expected

### ISSUE THREAD

**Issue by njbmartin** [CoraleStudios/Colore#61]
Had a look through the SDK sample application and can only find references to RGB and not RGBA, leading me to believe it only supports RGB.

Using alpha like so:

    new Color(255,255,255,0.5f);
Results in the keys being set to black.

Within my own application, I am using the following to resolve this:

        Color RGBAFix(Color color)
        {
            var a = color.A;
            return new Color(
                (1 - a) * 0 - a * color.R,
                (1 - a) * 0 - a * color.G,
                (1 - a) * 0 - a * color.B
            );
        }

**Comment by Sharparam** [comment]
There is currently no `Color` constructor supporting `(byte, byte, byte, float)`, so not sure what that's from.

The SDK docs say that alpha is supported "where applicable" (see screenshot below).

![Screenshot showing documentation for RZCOLOR](http://rfl.im/KY)

As for how they treat the alpha (0 transparent, or 0 opaque?) is unknown currently, we should contact them and ask.

**Comment by brandonscott** [comment]
This also references #25 where we had discussed similar things before.  I'll review my emails shortly to ensure I didn't get a response earlier in the year, and if not, I will ping an email off to Mark.

**Comment by Sharparam** [comment]
#25 was made before the note about alpha support appeared in the docs. Back then the discussion was about having Colore support alpha on its own, converting to RGB when passing to Chroma.

**Comment by njbmartin** [comment]
Ok, so I swapped it over to use floats, and it looks like only the Mousepad supports RGBA, and the alpha has been incorrectly implemented (0= opaque, 1 = transparent).

The above ensures support across all devices by converting them to RGB.

**Comment by brandonscott** [comment]
Interesting! So they did intend to support Alpha, but they just haven't done so consistently.  I'll enquire, Nico, would you like to make the bug fix for alpha implementation in Colore, or would you like me to?

**Comment by njbmartin** [comment]
More than happy to contribute. Will most likely do it tomorrow.

**Comment by brandonscott** [comment]
Cheers, that would be awesome, can review tomorrow.

**Comment by brandonscott** [comment]
As one might expect, other C# implementations of Alpha point towards 1 being opaque rather than transparent.  Colore currently treats 1 as opaque, as above, which in my opinion is correct.  Thoughts @njbmartin ?

**Comment by njbmartin** [comment]
@brandonscott when I said `incorrectly implemented (0= opaque, 1 = transparent)`, I meant that is how Razer have implemented. The correct way is (1= opaque, 0 = transparent).

**Comment by brandonscott** [comment]
Yes, I thought you did also but @Sharparam confused me thinking it was a Colore bug!  No worries, I thought that was the case anyway and am just finishing up an email.

**Comment by njbmartin** [comment]
Engineer's response:
> Transparency currently not supported at the moment.

**Comment by brandonscott** [comment]
Delaying this until v4.0 as bandwidth is limited until end of November.

**Comment by brandonscott** [comment]
I'll raise this problem again now CES is over with.

**Comment by Sharparam** [comment]
Closing this as `Color` will be needing a redesign that takes alpha completely out anyway.

**Comment by brandonscott** [comment]
^^ References 1.6.1 changes.
