### ISSUE TITLE
Mouse.Effects.Effect.None throws an exception

### ISSUE THREAD

**Issue by njbmartin** [CoraleStudios/Colore#62]
This was my fault for not implementing it correctly in #44 

For the mouse, this needs to be implemented slightly differently than the rest of the devices. Here's how the SDK Sample Application does it:

            ChromaSDK::Mouse::STATIC_EFFECT_TYPE NoEffect = {};
            NoEffect.LEDId = RZLED_ALL;
            CreateMouseEffect(ChromaSDK::Mouse::CHROMA_NONE, &NoEffect, NULL);

Need to change NativeWrapper.cs slightly to implement this:

        internal static Guid CreateMouseEffect(Razer.Mouse.Effects.Effect effect)
        {
            if (effect == Razer.Mouse.Effects.Effect.None)
            {
                return CreateMouseEffect(effect, new Razer.Mouse.Effects.None(Razer.Mouse.Led.All));
            }
            return CreateMouseEffect(effect, IntPtr.Zero);
        }

**Comment by brandonscott** [comment]
Will this be the same for `CreateMousepadEffect(Razer.Mousepad.Effects.Effect)` + `CreateKeyboard(Razer.Keyboard.Effects.Effect)` + `CreateKeypad(Razer.Keypad.Effects.Effect)` or just the one you have mentioned?

**Comment by njbmartin** [comment]
Everything else works as expected. Only the mouse doesn't like it.

However, having tested this new method with a flashing animation, you cannot call `SetAll()` immediately after, unlike the rest of the methods and devices.

**Comment by njbmartin** [comment]
Here's the engineers response as to why this behaves slightly differently:
>The reason is because of the nature of the LED control was exposed in the firmware. Older products (i.e. Deathadder Chroma) have separate LED controls while newer ones (Mamba TE, etc) have 1 control for all LEDs. However we do note that consistency is still an issue (albeit a minor one), we will put this into our design consideration for the next iteration.

**Comment by brandonscott** [comment]
Any progress or updates on this one?

**Comment by njbmartin** [comment]
Implemented as suggested above, however it is slower than other devices and requires the thread to sleep for at least 2 milliseconds (at least on my machine) in order to then set another effect.

However, #72 may resolve the issue of needing to perform this in the first place.

**Comment by Sharparam** [comment]
Fixed in #80
