### ISSUE TITLE
Configure version management

### ISSUE THREAD

**Issue by Sharparam** [CoraleStudios/Colore#7]
We need to set up how we are going to manage versioning of the project in a clean and hassle-free way.

**Comment by Sharparam** [comment]
I propose we use the `master` branch purely as a "tagged release" branch and let AppVeyor create release packages whenever code is pushed to that branch.

Any branch named `release-*` is to be used for release preparation (updating versions et.c).

Thoughts?

**Comment by brandonscott** [comment]
I agree.  We should use a `develop` and `feature/*` branching system for development as well to allow a cleaner view of the code base with easy promotion up through the branches to `master`.

**Comment by Sharparam** [comment]
As it is now, AppVeyor should create new versions whenever a commit is done to the `master` branch and publish it to GitHub and NuGet. As we haven't done such a push/merge yet, we have to wait and see how it works out.

**Comment by Sharparam** [comment]
Closing this issue as everything should be in order. Reopening if it turns out something goes horribly wrong.
