### ISSUE TITLE
Get Coveralls back

### ISSUE THREAD

**Issue by Sharparam** [CoraleStudios/Colore#74]
We need a way to report coverage to Coveralls again, quick googling doesn't reveal and obvious ways to integrate TeamCity with Coveralls, any ideas?

**Comment by brandonscott** [comment]
Do they have web hooks etc?  I know they have a server stand-alone version, we could look at using that?

**Comment by brandonscott** [comment]
Can we close this @Sharparam ?

**Comment by Sharparam** [comment]
Implemented in #133
