### ISSUE TITLE
Allow conversion between Razer's keys and .NET

### ISSUE THREAD

**Issue by Sharparam** [CoraleStudios/Colore#77]
When wanting to set a key, it could be useful to be able to send in the keycodes obtained from various Windows and .NET APIs. That would simplify things like setting colors on keys in response to certain events.

Possible ways to implement this? A manual dictionary to map Razer key values to/from .NET/Windows ones will of course work, but is incredibly tedious.

We should look into seeing if there are more efficient ways of doing the conversion that requires less manual labour (and thus probably more future-proof as well).

**Comment by brandonscott** [comment]
Yes, through some research and discussions on Slack, I cannot think of an extensible method of implementation here.

I think Razer's implementation, without remembering the exact keycodes, is mostly for OEM keys etc.

**Comment by Sharparam** [comment]
Razer's implementation is because the enum values correspond to columns and rows. `0xRRCC`, or the other way around, where `RR` = row and `CC` = column.

**Comment by brandonscott** [comment]
Any further thoughts on how we can proceed with this; is manual mapping an extensible and maintainable option?  If the answer to that question is no, we should consider the use of adding this enhancement.

**Comment by Sharparam** [comment]
Not sure what would be a good way to implement it. The enums differ a lot in what keys exist and which ones don't, neither of the WinForms or WPF key enums can be mapped entirely to the Razer one. Some keys just don't seem to have counterparts on Razer's side.

**Comment by Sharparam** [comment]
Adding this to the v4.0 milestone, we should aim at making a decision on this matter by that time.

**Comment by brandonscott** [comment]
I cannot think of a neat way to implement this, without a custom dictionary which is simply not maintainable.  

The value that this issue would give us is rather than each developer manually mapping key values in a control structure, the library would do it as a passthrough.

The only other way would be for Razer to refer to their enum values as the keycode values, but this seems unlikely.

Where do you guys feel we should go with this?

**Comment by Sharparam** [comment]
I'm leaning on not implementing it, the level of work required to maintain and test it doesn't seem worth it. We also can't ensure that the mapping will be correct, as there are some differences between Razer keys and WPF/WinForm keys, missing entries, and also duplicate entries.

**Comment by Sharparam** [comment]
Closing this due to lack of ideas and being kind of outside the scope of Colore.

Re-open if some ground-breaking idea is found.
