### ISSUE TITLE
Corale.Colore.Core.Color

### ISSUE THREAD

**Issue by Uhehesh** [CoraleStudios/Colore#78]
Are you serious having such a name?
I hope that you aren't.

Could you please add a coral color, so that it would be `Corale.Colore.Core.Color.Coral`?
That would make me so happy. Thanks a lot.

**Comment by brandonscott** [comment]
Hey, thanks for posting.  Do you find there is a genuine readability issue here?

If so, do you have any thoughts or examples of what we might use instead?

**Comment by Uhehesh** [comment]
I think the best solution is to change your studio name.

**Comment by bacondropped** [comment]
@Uhehesh, I doubt it will solve whatever particular problem you have. The qualified id will look like `Something.Colore.Core.Color` which still suggests a certain form of alliteration.

**Comment by njbmartin** [comment]
Maybe we'll add it in as a little easter egg, as a nod to @Uhehesh's suggestion!

**Comment by Uhehesh** [comment]
@njbmartin Great! I also like the fact you're a collar-borator.

**Comment by njbmartin** [comment]
O rly?

**Comment by Uhehesh** [comment]
@njbmartin Yeah. Corals everywhere. Great.

**Comment by brandonscott** [comment]
Far too much fun for a GitHub issue!  I'm kidding, but yeah, closing to tidy up.
