### ISSUE TITLE
Generalise struct field accessibility

### ISSUE THREAD

**Issue by Sharparam** [CoraleStudios/Colore#84]
Currently the effect struct fields have mixed declarations between being `public readonly` and simply `public`. We should move to having the same type of accessibility on all fields on all structs.

Should we have them `public` or `public readonly`?

**Comment by brandonscott** [comment]
Can you provide an example of what you'd like to change?

**Comment by Sharparam** [comment]
[The `Breathing` effect for keyboard has regular fields.](https://github.com/CoraleStudios/Colore/blob/develop/Corale.Colore/Razer/Keyboard/Effects/Breathing.cs)

[The `Breathing` effect for mousepad has `readonly` fields.](https://github.com/CoraleStudios/Colore/blob/develop/Corale.Colore/Razer/Mousepad/Effects/Breathing.cs)

Structs in C# are typically designed to be immutable so that is probably the path we should take (readonly fields), thoughts?

**Comment by njbmartin** [comment]
Makes sense to me. Good suggestion.

**Comment by brandonscott** [comment]
As Structs should be immutable in C#, I agree with this change to make them so.

**Comment by Sharparam** [comment]
I'll do the change tomorrow.

**Comment by Sharparam** [comment]
Fixed in #119
