### ISSUE TITLE
Add IsKeySafe flag to indicate potential ghosting issue

### ISSUE THREAD

**Issue by brandonscott** [CoraleStudios/Colore#90]
During the implementation of Snake for Chroma it became apparent that the virtual grid that Chroma SDK implements is not representative of the physical device.

Currently the proposed work around is to check for specific keys and exclude them from being used where possible.  A future implementation would be to either detect physical keyboard layout at firmware level to support multiple devices OR give users region specific information (multiple device incompatible.

**Comment by brandonscott** [comment]
ExcludedKeys reference: https://gist.github.com/brandonscott/1b37041bf623db2ddc2b

**Comment by Sharparam** [comment]
Implemented in #109
