### ISSUE TITLE
Passing RGB into Core.Color Returns Incorrect Color

### ISSUE THREAD

**Issue by brandonscott** [CoraleStudios/Colore#92]
When passing in RGB values into `Corale.Colore.Core.Color()`, the values of the color are wrong.  This has something to do with our conversion to AABBGGRR.

Currently I pass in BRG to get the desired color.

**Comment by Sharparam** [comment]
Was this on all RGB constructors or only certain types?

**Comment by brandonscott** [comment]
I'll double check my test.

**Comment by brandonscott** [comment]
Led to believe this was caused by incorrect input data.
